# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: 'ali'
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost

development:
  <<: *default
  database: eventspaces_development

test:
  <<: *default
  database: eventspaces_test

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: go_venues_db
  host: go-venues-database.cbke20q08g0v.ap-south-1.rds.amazonaws.com
